services:
  birthday-bot:
    build: .
    container_name: birthday-bot
    # restart: unless-stopped
    
    volumes:
      - app-data:/usr/src/app/database
      - ./.env:/usr/src/app/.env:ro

volumes:
  app-data: